#cmakedefine HAVE_SINF
#cmakedefine HAVE_SETENV
#cmakedefine HAVE_DLFCN_H
#cmakedefine HAVE_INTTYPES_H
#cmakedefine HAVE_MALLOC_H
#cmakedefine HAVE_MEMORY_H
#cmakedefine HAVE_STDINT_H
#cmakedefine HAVE_STDLIB_H
#cmakedefine HAVE_STRINGS_H
#cmakedefine HAVE_STRING_H
#cmakedefine HAVE_SYS_STAT_H
#cmakedefine HAVE_SYS_TYPES_H
#cmakedefine HAVE_UNISTD_H
